backend:
  build: ./backend
  container_name: project_backend
  restart: unless-stopped
  env_file:
    - .env
  environment:
    - MYSQL_HOST=db
    - MYSQL_DATABASE=${MYSQL_DATABASE}
    - MYSQL_USER=${MYSQL_USER}
    - MYSQL_PASSWORD=${MYSQL_PASSWORD}
  depends_on:
    db:
      condition: service_healthy
  healthcheck:
    test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
    interval: 10s
    timeout: 3s
    retries: 5
  networks:
    - internalnet
