version: "3.8"

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - internalnet

  backend:
    build: ./backend
    restart: unless-stopped
    env_file: .env
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    depends_on:
      db:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 10s
      timeout: 3s
      retries: 5
    networks:
      - internalnet

  nginx:
    image: nginx:stable
    restart: unless-stopped
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/index.html:/usr/share/nginx/html/index.html:ro
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - internalnet

volumes:
  db_data:

networks:
  internalnet:
    driver: bridge
