name: CI

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: rootpass
          MYSQL_DATABASE: appdb
          MYSQL_USER: appuser
          MYSQL_PASSWORD: apppass
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost"
          --health-interval=10s --health-timeout=5s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Wait for MySQL
        run: |
          for i in $(seq 1 30); do
            mysqladmin ping -h 127.0.0.1 -uroot -prootpass && break
            sleep 2
          done

      - name: Init DB
        run: mysql -h 127.0.0.1 -uroot -prootpass < db/init.sql

      - name: Run tests
        run: |
          cd backend
          npm test
